### ISSUE TITLE
Availability is being destroyed when an appointment is made

### ISSUE THREAD

**Issue by mikelikesbikes** [Devbootcamp/mentor-pairing#42]
In theory this means that a mentor could lose an availability in a specific case:
1. Mentor creates an Availability
2. Mentee creates an Appointments (thus destroying the Availability)
3. Mentee then destoys the Appointment
4. Mentor no longer has the original Availability, in spite of it being unclaimed.

We should be able to fix this by making Availability into a state machine, or alternatively, making it "has_one" Appointment. This way if the Appointment is destroyed we can put the Availability back into the pool for someone else to claim.

**Comment by Lzdanowicz** [comment]
Tasks @mikelikesbikes and I plan on tackling:

1. add association between `Appointment` and `Availability`.
   * migration
   * model wiring
2. create reader methods for `Appointment` fields to reference the `availability` association instead (stop using the fields on `appointments`.
3. remove `kill_availability` and `parse_availability` callbacks.
4. scope `Availability` to only those that don't have an `appointment`
5. rake task to backfill `availability` association for all previously created `appointments`
6. migration to remove the extra fields from `appointments`

@ltw @redsquirrel @alycit, thoughts?

**Comment by ltw** [comment]
:+1: This sounds great.

**Comment by Lzdanowicz** [comment]
Adding to 1. we need to update `Availability#visible` to return only availabilities that aren't associated with an `Appointment`.
