### ISSUE TITLE
Tabs or other mechanism for location filtering

### ISSUE THREAD

**Issue by alycit** [Devbootcamp/mentor-pairing#99]
It would be great if we could have Chicago, NYC, SF tabs or some mechanism on the main page to quickly filter on the big 3 locations.

**Comment by alycit** [comment]
@ltw @arnamak So I think I will take this on.  I have interest in figuring this out ahead of getting ready for localhost.  The hardest part for me is to figure out how this will look and keep the aesthetic of the site for people looking for a mentor.  Want to keep it tight.  

From a filtering standpoint...Should we make it use location services to figure out nearest location, and then choose remote if there isn't an obvious one? Or just build a filter that shows a unique list of offering locations?

For creating an offering... I don't think Wellington uses this app, so just keep it for the big 3, Columbus and Remote, then have an 'other' field where we can enter a location?

Thoughts?

**Comment by alycit** [comment]
I just realized Location and City are separate.  Forgot about that.  Feel like these 2 field don't necessarily meet our needs anymore.  Need to figure that out.  @ltw

**Comment by ltw** [comment]
As part of this, can we update the wording on the form for clarity? Something like:

![screen shot 2015-01-19 at 13 59 05](https://cloud.githubusercontent.com/assets/42032/5806933/738e6714-9fe3-11e4-9123-f62fc2972e0f.png)

**Comment by ltw** [comment]
Let's add Columbus as a "Mentor Students From" option.

**Comment by alycit** [comment]
I know we merged my branch... however, I need to add a little thing for when a filter option has no offerings.  Oops.  I'll get that out asap.
